### ISSUE TITLE
Project dependency aliases don't resolve in editor

### ISSUE THREAD

**Issue by bvalyou** [apple/pkl-intellij#19]
Trying to leverage Pkl projects with the IntelliJ Plugin. When using project dependencies, the plugin loses all context on the dependencies, even after running `pkl project resolve`.

Plugin Version 0.26.0

IntelliJ IDEA 2023.3.4 (Ultimate Edition)
Build #IU-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3.1

<img width="657" alt="image" src="https://github.com/apple/pkl-intellij/assets/16170157/05075302-fcf1-4eb5-81bd-9c314f408b08">

The red underline for ObjectMeta says "Unresolved reference: ObjectMeta"

If I replace `@k8s` with its url from PklProject, everything looks good.

<img width="784" alt="image" src="https://github.com/apple/pkl-intellij/assets/16170157/e50dadda-a38c-46a2-98ab-6b1e88233f5e">

Thanks for the great work on this to date!

**Comment by bvalyou** [comment]
I tried looking into this myself but not really sure where to start. It would be a big help if this could get some attention

**Comment by holzensp** [comment]
Apologies; missed this. The plugin knows how to hold the CLI, so you should never have to `pkl project resolve` to inform the plugin. When you open the corresponding `PklProject` file, do you see a top-bar offering you to `Sync Pkl project` (as in attached screenshot)? If so, click that `Sync` and revisit your file.

<img width="371" alt="Screenshot 2024-04-02 at 15 25 03" src="https://github.com/apple/pkl-intellij/assets/1875918/35a0417e-e7a0-4e34-a89f-d9d5d543c8f1">

**Comment by bvalyou** [comment]
Doh! That was it! Thank you!
