### ISSUE TITLE
Bug: Transitive dependency type matching fails

### ISSUE THREAD

**Issue by bvalyou** [apple/pkl-intellij#29]
I've created a minimal reproduction repo

https://github.com/bvalyou/pkl-intellij-transitive-deps-bug

If you open https://github.com/bvalyou/pkl-intellij-transitive-deps-bug/blob/main/project2/consumer.pkl in IntelliJ you'll be able to see the error case and couple of similar cases that don't trigger the error.

<img width="701" alt="image" src="https://github.com/apple/pkl-intellij/assets/16170157/b58a25ff-3382-4a26-88af-af3b0e7aff71">

IntelliJ IDEA 2024.1.1 (Ultimate Edition)
Build #IU-241.15989.150, built on April 29, 2024

Plugin version 0.26.0

**Comment by bvalyou** [comment]
@stackoverflow @bioball @holzensp Bumping this up for line of sight

**Comment by bvalyou** [comment]
@stackoverflow @bioball @holzensp

**Comment by stackoverflow** [comment]
Thanks for the report. This most probably happens because this dependency comes from two separate imports (one from project1 and the other from project2) and IntelliJ couldn't tell they are actually the same package and version.

**Comment by bvalyou** [comment]
Would it be possible to merge the caches?

**Comment by bioball** [comment]
The reason this is happening is because we put all the dependencies of `project1` in `~/.pkl/editor-support/<path-to-project1>`, and project2 in `~/.pkl/editor-support/<path-to-project2>`.

We do this so that we can resolve transitive remote dependencies _within_ this project correctly. Looks like we aren't accounting for transitive deps between two local projects, though.

Not sure what the solution to this problem is right now, but this is definitely a bug that needs solving.

**Comment by bvalyou** [comment]
It's actually not limited to local projects, just simpler to demonstrate in the repo. The same thing happens if I publish a lib with an interface referencing k8s and consume it from another project.

**Comment by bioball** [comment]
In my understanding of the bug, this should only happen in the case of multi-project repos, and is more or less the same issue as https://github.com/apple/pkl-intellij/issues/23.

Are you seeing this in a single project repo?

**Comment by bvalyou** [comment]
Yes; I have an internal library published to a Sonatype raw repo that has an interface with `Listing<K8sResource>` as a member. In another repo I pull that lib and pass it a NetworkPolicy (same k8s version) and it says "Type mismatch. Required: K8sResource, Found: NetworkPolicy"

**Comment by bioball** [comment]
@bvalyou this should be fixed in 0.28.0. Can you check to see if this fixes it on your side?

**Comment by bvalyou** [comment]
Yes I confirmed this afternoon, very excited about this! Thanks!
