### ISSUE TITLE
[Feature Request] Render Doc comment Markdown Tables in Editor

### ISSUE THREAD

**Issue by moritz-t-w** [apple/pkl-intellij#30]
Currently GitHub flavored Markdown tables don't appear to be supported by the intellij extension. However the [Documentation](https://pkl-lang.org/main/current/language-reference/index.html#doc-comments) specifies that Tables are supported.
![image](https://github.com/apple/pkl/assets/90388353/2a05e244-3e73-4738-9ad2-6f5247b36b3a)

**Comment by bioball** [comment]
This works, but you need to add a newline between the previous paragraph and the start of your table.

For example:

```
/// Some paragraph
/// 
/// | Foo | Bar |
/// | --- | --- |
/// | 1 | 2 |
/// | 3 | 4 |
foo: String
```

Produces:

![Screenshot 2024-05-15 at 1 22 04 PM](https://github.com/apple/pkl-intellij/assets/4590460/97f266cf-2df1-4812-9e1f-d8c6115953e3)
