### ISSUE TITLE
Pkl IntelliJ plugin incompatible with IntelliJ release 2024.2

### ISSUE THREAD

**Issue by jae226** [apple/pkl-intellij#50]
[IntelliJ 2024.2](https://blog.jetbrains.com/idea/2024/08/intellij-idea-2024-2) was released on August 7, 2024.

The Pkl IntelliJ plugin is incompatible with the release
<img width="1174" alt="Screenshot 2024-08-07 at 10 17 45 AM" src="https://github.com/user-attachments/assets/f663b17f-e269-4ea7-a16c-0b60093a0f55">

**Comment by stackoverflow** [comment]
Fixed in 0.29.0
